# Generated by Django 5.2.3 on 2025-06-17 05:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A human-readable name for the goal (e.g., 'User Registration').", max_length=255, verbose_name='Goal Name')),
                ('event_name', models.CharField(help_text="The 'Event Name' that triggers this goal's conversion.", max_length=100, unique=True, verbose_name='Trigger Event Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Goal',
                'verbose_name_plural': 'Goals',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_seen', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('browser_family', models.CharField(blank=True, max_length=100)),
                ('browser_version', models.CharField(blank=True, max_length=50)),
                ('os_family', models.CharField(blank=True, max_length=100)),
                ('os_version', models.CharField(blank=True, max_length=50)),
                ('device_family', models.CharField(blank=True, default='Desktop', max_length=100)),
                ('device_brand', models.CharField(blank=True, max_length=100)),
                ('device_model', models.CharField(blank=True, max_length=100)),
                ('is_mobile', models.BooleanField(default=False)),
                ('is_tablet', models.BooleanField(default=False)),
                ('is_touch', models.BooleanField(default=False)),
                ('is_pc', models.BooleanField(default=False)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('referrer_url', models.URLField(blank=True, max_length=2048)),
                ('referrer_domain', models.CharField(blank=True, db_index=True, max_length=255)),
                ('utm_source', models.CharField(blank=True, db_index=True, max_length=255)),
                ('utm_medium', models.CharField(blank=True, db_index=True, max_length=255)),
                ('utm_campaign', models.CharField(blank=True, db_index=True, max_length=255)),
                ('utm_term', models.CharField(blank=True, max_length=255)),
                ('utm_content', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ap_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=2048)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('time_on_page_seconds', models.PositiveIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pageviews', to='activity_pulse.session')),
            ],
            options={
                'verbose_name': 'Page View',
                'verbose_name_plural': 'Page Views',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Event Name')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('properties', models.JSONField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='activity_pulse.session')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsDashboard',
            fields=[
            ],
            options={
                'verbose_name': 'Pulse Dashboard',
                'verbose_name_plural': 'Pulse Dashboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('activity_pulse.session',),
        ),
    ]
