# Generated by Django 5.2.3 on 2025-06-14 13:26

import django.db.models.deletion
import reports.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=reports.models.report_media_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('issue_type', models.CharField(help_text="e.g., 'Overflowing Bin', 'Broken Streetlight', 'Pothole'", max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('ACTIONED', 'Action Taken'), ('DUPLICATE', 'Duplicate')], db_index=True, default='PENDING', max_length=20)),
                ('moderator_notes', models.TextField(blank=True, help_text="Internal notes for moderators/admins regarding the report's status.", null=True)),
                ('action_taken_notes', models.TextField(blank=True, help_text='Details of the action taken by the municipality to resolve the issue.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='locations.location')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
