# Generated by Django 5.2.3 on 2025-06-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='points_awarded',
            field=models.PositiveIntegerField(default=0, help_text='Points awarded for this report submission.'),
        ),
    ]
