# Generated by Django 5.2.3 on 2025-06-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_points_awarded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='points_awarded',
            field=models.IntegerField(default=0, help_text='Points awarded or deducted for this report submission.'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified & Awaiting Action'), ('REJECTED', 'Rejected'), ('IN_PROGRESS', 'Action In Progress'), ('ACTIONED', 'Action Taken')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='reportstatushistory',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified & Awaiting Action'), ('REJECTED', 'Rejected'), ('IN_PROGRESS', 'Action In Progress'), ('ACTIONED', 'Action Taken')], max_length=20),
        ),
    ]
