# Generated by Django 5.2.3 on 2025-06-11 08:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="The common name of the location (e.g., 'City Park Main Entrance').", max_length=255)),
                ('description', models.TextField(blank=True, help_text='A brief description of the location.')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('location_type', models.CharField(choices=[('TOILET', 'Public Toilet'), ('BUS_STAND', 'Bus Stand'), ('PARK', 'Park'), ('STREET', 'Street'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['name'],
            },
        ),
    ]
