# Generated by Django 5.2.3 on 2025-06-14 13:26

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import locations.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Common name of the location, e.g., 'Main Street Park - Gate A'.", max_length=255)),
                ('description', models.TextField(blank=True, help_text='A brief description or additional details about the location.')),
                ('point', django.contrib.gis.db.models.fields.PointField(help_text='The precise geographic coordinate of the location.', srid=4326)),
                ('location_type', models.CharField(choices=[('PUBLIC_TOILET', 'Public Toilet'), ('BUS_STAND', 'Bus Stand'), ('PARK', 'Park'), ('STREET_SEGMENT', 'Street Segment'), ('PUBLIC_BIN', 'Public Bin'), ('GOVERNMENT_OFFICE', 'Government Office'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=30)),
                ('qr_code_image', models.ImageField(blank=True, editable=False, null=True, upload_to=locations.models.qr_code_upload_path)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive locations cannot have new reports filed against them.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('municipality', models.ForeignKey(help_text='The governing municipality for this location.', on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='subscriptions.municipality')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['municipality', 'name'],
            },
        ),
    ]
