# Generated by Django 5.2.3 on 2025-06-15 12:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='badges/icons/')),
                ('required_points', models.PositiveIntegerField(default=0, help_text='Total points required to earn this badge.')),
                ('required_reports', models.PositiveIntegerField(default=0, help_text='Number of initial reports (not verifications) required.')),
                ('required_verifications', models.PositiveIntegerField(default=0, help_text='Number of verifications required.')),
            ],
        ),
        migrations.CreateModel(
            name='LotteryTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PointLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('reason', models.CharField(choices=[('INITIAL_REPORT', 'New Issue Reported'), ('PEER_VERIFICATION', 'Verified an Issue'), ('ADMIN_BONUS', 'Admin Bonus'), ('REPORT_REJECTED', 'Penalty: Rejected Report'), ('LOTTERY_WIN', 'Lottery Prize')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('logo', models.ImageField(upload_to='sponsors/logos/')),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('drawn_at', models.DateTimeField(blank=True, null=True)),
                ('municipality', models.ForeignKey(help_text='The lottery is available to citizens active in this municipality.', on_delete=django.db.models.deletion.CASCADE, related_name='lotteries', to='subscriptions.municipality')),
            ],
        ),
    ]
