# Generated by Django 5.2.3 on 2025-06-11 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Point Log'},
        ),
        migrations.AddField(
            model_name='badge',
            name='required_points',
            field=models.PositiveIntegerField(default=0, help_text='Points required to earn this badge.'),
        ),
        migrations.AddField(
            model_name='badge',
            name='required_reports',
            field=models.PositiveIntegerField(default=0, help_text='Number of reports required.'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='icon_url',
            field=models.URLField(blank=True, help_text='URL to the badge icon image.', null=True),
        ),
        migrations.AlterField(
            model_name='pointlog',
            name='reason',
            field=models.CharField(choices=[('INITIAL_REPORT', 'First Report for an Issue'), ('PEER_VERIFICATION', 'Peer Verification of an Issue'), ('ADMIN_BONUS', 'Admin-Awarded Bonus')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_to', to='gamification.badge'),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to=settings.AUTH_USER_MODEL),
        ),
    ]
