# Generated by Django 5.2.3 on 2025-06-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_points',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
