# Generated by Django 5.2.3 on 2025-06-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_total_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='total_points',
            field=models.IntegerField(default=0, help_text='Denormalized total points for performance.'),
        ),
    ]
