# Generated by Django 5.2.3 on 2025-06-14 13:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_locations', models.PositiveIntegerField(help_text='Maximum number of QR-coded locations allowed.')),
                ('max_admins', models.PositiveIntegerField(help_text='Maximum number of municipal admin/moderator accounts.')),
                ('analytics_access', models.BooleanField(default=False, help_text='Grants access to the advanced analytics dashboard.')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Controls access for the entire municipality. Deactivates on subscription expiry.')),
                ('subscribed_until', models.DateField(blank=True, null=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='municipalities', to='subscriptions.subscriptionplan')),
            ],
            options={
                'verbose_name_plural': 'Municipalities',
                'ordering': ['state', 'name'],
            },
        ),
    ]
